jarvis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learn.urls')),
]

learn/urls.py
from django.urls import path
from . import views
from .views import natija

app_name = 'learn'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('natija/',natija.as_view(), name='natija'),
    path('exams/', views.ExamListView.as_view(), name='exams'),
    path('notes/', views.NotesListView.as_view(), name='notes'),

    path('mathematics/exams/<int:pk>/', views.MathExamView, name='math_exams'),
    # path('mathematics/notes/',),

    path('science/exams/<int:pk>/', views.ScienceExamsView, name='science_exams'),
    # path('science/notes/',),

]

learn/models.py
from django.db import models


class Subject(models.Model):
    name          = models.CharField(max_length = 20)

    def __str__(self):
        return self.name


class Exam(models.Model):
    name           = models.CharField(max_length=20)
    subject        = models.ForeignKey(Subject,on_delete=models.CASCADE)
    score          = models.IntegerField(default=0)
    
    class Meta:
        order_with_respect_to = 'name'

    def __str__(self):
        return self.name


class Question(models.Model):
    exam            = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question_text   = models.TextField(max_length = 255, null = False)

    class Meta:
        order_with_respect_to = 'exam'

    def __str__(self):
        return "%s" % (self.question_text)


class Choice(models.Model):
    question        = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text     = models.CharField(max_length = 255, null = False)
    is_correct      = models.BooleanField(blank=True)
    
    class Meta:
        order_with_respect_to = 'question'

    def __str__(self):
        return self.choice_text

learn/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, ListView

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Exam, Question, Subject, Choice


class  IndexView(ListView):
    template_name = 'learn/index.html'
    context_object_name = 'subject_list'
    
    def get_queryset(self):
        return Subject.objects.all()

class  natija(ListView):
    template_name = 'learn/natija.html'
class ExamListView(ListView):
    template_name = 'learn/list/exam_list.html'
    context_object_name = 'subject_list'
    
    def get_queryset(self):
        return Subject.objects.all()


class NotesListView(ListView):
    template_name = 'learn/list/notes_list.html'
    context_object_name = 'subject_list'
    
    def get_queryset(self):
        return Subject.objects.all()


def MathExamView(request, pk):
    exam = get_object_or_404(Exam, pk=pk)    
    quest_list = exam.question_set.all()
    quest_length = len(quest_list)
    page = request.GET.get('question', 1)
    paginator = Paginator(quest_list, 1)

    try:
        quest = paginator.page(page)

    except PageNotAnInteger:
        quest = paginator.page(1)

    except EmptyPage:
        quest = paginator.page(paginator.num_pages)
    
    question = get_object_or_404(Question, pk=page)
    choice_list = question.choice_set.all()

    return render(request, 'learn/exams/math.html',
        {
        'quest': quest, 
        'quest_length': quest_length,
        'choice': choice_list
        }) 


def ScienceExamsView(request, pk):
    exam = get_object_or_404(Exam, pk=pk)    
    quest_list = exam.question_set.all()
    quest_length = len(quest_list)
    page = request.GET.get('question', 1)
    paginator = Paginator(quest_list, 1)

    try:
        quest = paginator.page(page)

    except PageNotAnInteger:
        quest = paginator.page(1)

    except EmptyPage:
        quest = paginator.page(paginator.num_pages)
    
    question = get_object_or_404(Question, pk=page)
    choice_list = question.choice_set.all()

    return render(request, 'learn/exams/math.html',
        {
        'quest': quest, 
        'quest_length': quest_length,
        'choice': choice_list
        }) 

learn/templates/learn/exams/english.html
{% extends 'learn/exams/exam_base.html' %}

learn/templates/learn/exams/exam_base.html
{% extends 'learn/generic_base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block exam %}
{% for q in quest %}
<div id="quest_card">
    <div class="card">
        {% if DoesNotExistError %} <p><strong>{{ DoesNotExistError }}</strong></p> {% endif %}
        <div class="card-header">
        <h5 class="text-center">{{q.exam}}</h5>
            <i></b>Question {{ q.id }} of {{ quest_length }} </i>
        </div>
        <div class="card-body">
            {{q.question_text}}
        </div>
        <div class="card-footer">
            {% for c in choice %}
            <div class="list-group">
  
                <input type="radio" name="RadioInputName" value="Value1" id="{{c.choice_text}}" />
                <label class="list-group-item" for="{{c.choice_text}}"> {{c.choice_text}}</label>
                
              </div> <br>
            {% endfor %}

            {% if quest.has_other_pages %}

            {% if quest.has_previous %}
            <a href="?question={{ quest.previous_page_number}}">
                <button class="btn btn-outline custom-btn float-left"> Previous</button>
            </a>
            {% endif %}

            {% if quest.has_next %}
            <a href="?question={{ quest.next_page_number}}">
                <button class="btn btn-outline custom-btn float-right" > Next</button>
            </a>
            {% else %}
            <a href="https://muqaddasresurspython.herokuapp.com/natija/">button class="btn btn-outline custom-btn float-right"> Finish</button></a><
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

learn/templates/learn/exams/kiswahili.html
{% extends 'learn/exams/exam_base.html' %}

learn/templates/learn/exams/math.html
{% extends 'learn/exams/exam_base.html' %}

learn/templates/learn/exams/religion.html
{% extends 'learn/exams/exam_base.html' %}

learn/templates/learn/exams/science.html
{% extends 'learn/exams/exam_base.html' %}

learn/templates/learn/exams/social.html
{% extends 'learn/exams/exam_base.html' %}

learn/templates/learn/generic_base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- jQuery added here to avoid "Uncaught Error: Bootstrap's JavaScript requires jQuery" -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Fonts -->
    <link
        href="https://fonts.googleapis.com/css2?family=Black+Ops+One&family=Montserrat:wght@300;700&family=Playfair+Display&display=swap"
        rel="stylesheet">
    <!-- Icons -->
    <script src="https://kit.fontawesome.com/b1eb41e9a4.js" crossorigin="anonymous"></script>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/png">

    <title>Muqaddas</title>
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
        <!-- <div class="container"> -->
        <a href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>
        <a class="navbar-brand" href="{% url 'learn:index' %}">Muqaddas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'learn:index' %}">Bosh sahifa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">



                <li class="nav-item">
                    <a class="nav-link" href="https://www.youtube.com/channel/UC-E3EzGzVXgTnXKAKY_argA/videos">Youtube</a>
                </li>
            </ul>
            <form class="form-inline" style="padding: 0px 10px;">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Izlash..." aria-label="Username">
                </div>
            </form>
        </div>
    </nav>
    <div style="min-height: 480px;">
        {% block landing %}
        {% endblock %}

        {% block subjects_list %}
        {% endblock %}

        {% block exam %}
        {% endblock %}

        {% block notes_list %}
        {% endblock %}
    </div>
    <!-- Footer -->
    <footer class="footer text-center shadow p-4 mb-2">
        <div class="container">
            <!-- <hr> -->
            <i class="fa fa-code"></i> with
            <i class="far fa-heart"></i> by
            <a href="https://github.com/Tim-is-Weird" target="_blank">
                <i class="fab fa-github" data-toggle="tooltip" data-placement="top" title="Timothy Wangwe"
                    style="color: azure; text-decoration: underline;"></i>
            </a> &
            <a href="https://github.com/ChrisAchinga" target="_blank">
                <i class="fab fa-github-alt" data-toggle="tooltip" data-placement="top" title="Chris Achinga"
                    style="color: azure; text-decoration: underline;"></i>
            </a>
        </div>
        <span class="font-weight-light float-left"> Copyright &copy; 2020 </span>
        <span class="font-weight-light float-right"> All Rights Reserved </span>
    </footer>
    <!-- Optional JavaScript -->
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
    <script>
        //Dropdown on hover
        $(document).ready(function () {
            $(".dropdown, .btn-group").hover(function () {
                var dropdownMenu = $(this).children(".dropdown-menu");
                if (dropdownMenu.is(":visible")) {
                    dropdownMenu.parent().toggleClass("open");
                }
            });
        });
        // Tooltip
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>

</html>

learn/templates/learn/index.html
{% extends 'learn/generic_base.html' %}
{% load static %}


{% block landing %}
<div class="row">
    <div class="col-sm-6">
        <img src="{% static 'img/students-on-computer.jpg' %}" alt="" srcset="" class="rounded img-fluid">
    </div>
    <div class="col-sm-6">
        <h1><b>Agar siz o'rgana olsangiz, <br> siz hamma narsani qilishingiz mumkin!! </b></h1>
        <hr class="custom">
        <p>
            Biz sizga o'rganish va o'sishni taklif qilgan ushbu bepul imkoniyatdan foydalaning. Siz eng yaxshi bo'ling.
        </p>
        <br>

            <div class="col-sm-4">
                <br>
                <i class="fas fa-user-graduate"></i>
                <p>
                    Resurslar jamlammasi
                </p>
                <a href="https://www.youtube.com/channel/UC-E3EzGzVXgTnXKAKY_argA/videos"> <button class="btn btn-outline"> O'rganish</button> </a>
            </div>
            <div class="col-sm-4">
                <br>
                <i class="fas fa-vials"></i>
                <p>
                   Testlar jamlammasi
                </p>
                <a href="{% url 'learn:exams' %}"> <button class="btn btn-outline"> Testlar yechish </button> </a>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}

learn/templates/learn/list/exam_list.html
{% extends 'learn/generic_base.html' %}
{% load static %}

{% block subjects_list %}
<div class="row">
    {% for subject in subject_list %}
    <div class="col-sm-4">
        <div class="card">
            <div class="card-footer">
                <b>
                    Python Exams
                </b>
            </div>
            <div class="underlay">
                <div class="photo-credit text-center">Photo by
                    <a href="https://pixabay.com" target="_blank" class="custom-link" style="color: #1ABC9C;">Ernesto Eslava </a> on
                    <a href="https://pixabay.com" target="_blank" class="custom-link" style="color: #1ABC9C;">Pixabay </a>
                </div>
                <img src="{% static 'img/students-on-computer.jpg' %}" alt="" class="rounded img-fluid img-hover">
                <div class="overlay">
                    <div class="text">
                        <a href="https://muqaddasresurspython.herokuapp.com/{{subject.name.lower}}/exams/{{subject.id}}/"> <button class="btn btn-outline"> Testni boshlash! </button> </a>
                    </div>
                </div>
            </div>
        </div>
        <br>
    </div>
    {% endfor %}
</div>
{% endblock %}

learn/templates/learn/list/notes_list.html
{% extends 'learn/generic_base.html' %}
{% load static %}

{% block subjects %}
<div class="row">

</div>
{% endblock %}

learn/templates/learn/natija.html
<h1>Siz 2 ta savolga javob topdingiz</h1>